update ci

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -24,6 +24,9 @@ jobs:
     if: github.repository == 'pyg-team/pytorch_geometric'
     # runs-on: ubuntu-latest
     runs-on: [self-hosted, nvidia]
+    container:
+      image: alpine:latest
+      options: --user root  # :(
     # container:
     #   image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
     #   options: '--gpus=all --ipc=host'
@@ -33,47 +36,47 @@ jobs:
       with:
         fetch-depth: '0'
 
-    - name: Clean up mamba from previous jobs
-      run: |
-        ls -al $HOME
-        rm -rf $HOME/.mambaforge
-        rm -rf $HOME/.conda
-        rm -rf $HOME/micromamba-bin
-        ls -al $HOME
+    # - name: Clean up mamba from previous jobs
+    #   run: |
+    #     ls -al $HOME
+    #     rm -rf $HOME/.mambaforge
+    #     rm -rf $HOME/.conda
+    #     rm -rf $HOME/micromamba-bin
+    #     ls -al $HOME
 
-    - uses: mamba-org/setup-micromamba@v1
-      with:
-        create-args: 'python=3.10'
-        init-shell: bash
+    # - uses: mamba-org/setup-micromamba@v1
+    #   with:
+    #     create-args: 'python=3.10'
+    #     init-shell: bash
 
-    - name: Check runner
-      run: |
-        echo $HOME
-        nvidia-smi
-        which python conda mamba || echo error
+    # - name: Check runner
+    #   run: |
+    #     echo $HOME
+    #     nvidia-smi
+    #     which python conda mamba || echo error
 
-    - name: Set up asv
-      run: |
-        python -m pip install -U pip
-        pip install "git+https://github.com/airspeed-velocity/asv.git@8f5c8af"
-        asv machine --machine "pyg-t4" --yes
+    # - name: Set up asv
+    #   run: |
+    #     python -m pip install -U pip
+    #     pip install "git+https://github.com/airspeed-velocity/asv.git@8f5c8af"
+    #     asv machine --machine "pyg-t4" --yes
 
-    - name: Configure Git
-      run: |
-        git config --local user.name "${{ github.actor }}"
-        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
-        git config --list
+    # - name: Configure Git
+    #   run: |
+    #     git config --local user.name "${{ github.actor }}"
+    #     git config --local user.email "${{ github.actor }}@users.noreply.github.com"
+    #     git config --list
 
-    - name: Run benchmarks on 2.3.0 and master
-      timeout-minutes: 10  # FIXME: Adjust timeout
-      run: |
-        git branch --all
-        asv run HASHFILE:HASHFILE.txt \
-          --launch-method spawn \
-          --skip-existing-successful \
-          --verbose \
-          --show-stderr \
-          --bench scatter  # FIXME: Run all benchmarks
+    # - name: Run benchmarks on 2.3.0 and master
+    #   timeout-minutes: 10  # FIXME: Adjust timeout
+    #   run: |
+    #     git branch --all
+    #     asv run HASHFILE:HASHFILE.txt \
+    #       --launch-method spawn \
+    #       --skip-existing-successful \
+    #       --verbose \
+    #       --show-stderr \
+    #       --bench scatter  # FIXME: Run all benchmarks
 
     # - name: Upload results
     #   uses: actions/upload-artifact@v3
